name: Testing executing of shell scripts

on: push

jobs:
    Run_script:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: My first multiline commit
          run: | 
            chmod +x ./dragonfetch.sh
            ./dragonfetch.sh
        